export const visibilityFilters = {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE'
}

export const actionTypes = {
    ADD_TODO: 'ADD_TODO',
    ADD_TODO_BLOCK: 'ADD_TODO_BLOCK',
    TOGGLE_TODO: 'TOGGLE_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    REMOVE_TODO_BLOCK: 'REMOVE_TODO_BLOCK',
    SELECT_TODO_BLOCK: 'SELECT_TODO_BLOCK',
    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
}
